import type { AnalyzedPaper } from "../types/analyzedPaper";

/** Fixture analyzed corpus for FD — mirrors draft12 negative paths + shelf winners. */
export const BIBLIOGRAPHY_FD: readonly AnalyzedPaper[] = [
  {
    ref: "31196103",
    step: "shelf",
    verdict: "shelf",
    reason: "International consortium consensus — core shelf anchor.",
    title:
      "Best practice management guidelines for fibrous dysplasia/McCune-Albright syndrome: a consensus statement from the FD/MAS international consortium",
    authors: "Javaid MK, Boyce A, Appelman-Dijkstra N, et al.",
    journal: "Orphanet J Rare Dis",
    year: 2019,
    access: "oa",
    category: "base_consensus",
    pmid: "31196103",
    bookshelf: null,
    changeProbability: null,
    suggestionId: null,
  },
  {
    ref: "NBK274564",
    step: "shelf",
    verdict: "shelf",
    reason: "Continuously updated NIH reference chapter.",
    title: "Fibrous Dysplasia / McCune-Albright Syndrome — GeneReviews®",
    authors: "Boyce AM, Collins MT, et al.",
    journal: "GeneReviews® · NCBI Bookshelf",
    year: "continuously updated",
    access: "oa",
    category: "reference_compendium",
    pmid: null,
    bookshelf: "NBK274564",
    changeProbability: null,
    suggestionId: null,
  },
  {
    ref: "38112233",
    step: "monitor",
    verdict: "suggestion",
    reason: "Stronger dosing evidence vs current denosumab guidance.",
    title: "Denosumab dosing in fibrous dysplasia — Leiden cohort update",
    authors: "Rotman-Pikielny P, et al.",
    journal: "J Bone Miner Res",
    year: 2025,
    access: "abstract",
    category: "",
    pmid: "38112233",
    bookshelf: null,
    changeProbability: 0.64,
    suggestionId: "sg-deno",
  },
  {
    ref: "40848713",
    step: "monitor",
    verdict: "rejected",
    reason: "Mechanism paper; nothing out-of-the-box for clinical guidance.",
    title: "Single-cell landscape of GNAS-mutant fibrous dysplasia",
    authors: "Chen X, et al.",
    journal: "Am J Hum Genet",
    year: 2025,
    access: "abstract",
    category: "",
    pmid: "40848713",
    bookshelf: null,
    changeProbability: 0.2,
    suggestionId: null,
  },
  {
    ref: "32115588",
    step: "shelf",
    verdict: "rejected",
    reason: "Narrative review without new data vs the consensus.",
    title: "Fibrous dysplasia: a narrative review",
    authors: "Kumar A, et al.",
    journal: "Cureus",
    year: 2020,
    access: "oa",
    category: "duplicate",
    pmid: "32115588",
    bookshelf: null,
    changeProbability: null,
    suggestionId: null,
  },
  {
    ref: "39008842",
    step: "monitor",
    verdict: "low",
    reason: "Weak signal — vitamin D adjunct, already covered in synthesis.",
    title: "Vitamin D supplementation in FD/MAS",
    authors: "Lee S, et al.",
    journal: "Bone",
    year: 2024,
    access: "paywall",
    category: "",
    pmid: "39008842",
    bookshelf: null,
    changeProbability: 0.05,
    suggestionId: null,
  },
] as const;

export const BIBLIOGRAPHY: Readonly<Record<string, readonly AnalyzedPaper[]>> = {
  fd: BIBLIOGRAPHY_FD,
};
