"""baseline: content domain schema (diseases, guideline_documents, content_prs, catalog_stats, care_pathways)

Revision ID: dd31c5539990
Revises: 
Create Date: 2026-05-16 15:47:30.147339

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dd31c5539990'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('catalog_stats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('disease_count', sa.Integer(), nullable=False),
    sa.Column('doctor_count', sa.Integer(), nullable=False),
    sa.Column('recruiting_trial_count', sa.Integer(), nullable=False),
    sa.Column('open_pr_count', sa.Integer(), nullable=False),
    sa.CheckConstraint('id = 1', name=op.f('ck_catalog_stats_single_row')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_catalog_stats'))
    )
    op.create_table('diseases',
    sa.Column('slug', sa.Text(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('name_short', sa.Text(), nullable=False),
    sa.Column('omim', sa.Text(), nullable=False),
    sa.Column('gene', sa.Text(), nullable=False),
    sa.Column('inheritance', sa.Text(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('types_json', sa.Text(), server_default='[]', nullable=False),
    sa.Column('related_json', sa.Text(), server_default='[]', nullable=False),
    sa.Column('prevalence_text', sa.Text(), nullable=False),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('status_by', sa.Text(), nullable=True),
    sa.Column('status_date', sa.Text(), nullable=True),
    sa.Column('ai_draft_date', sa.Text(), nullable=True),
    sa.Column('open_prs', sa.Integer(), server_default='0', nullable=False),
    sa.Column('doctors_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('trials_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('coverage', sa.Text(), nullable=False),
    sa.Column('accent', sa.Text(), nullable=False),
    sa.Column('guideline_prompt_profile_json', sa.Text(), server_default='{}', nullable=False),
    sa.PrimaryKeyConstraint('slug', name=op.f('pk_diseases'))
    )
    op.create_table('care_pathways',
    sa.Column('disease_slug', sa.Text(), nullable=False),
    sa.Column('locale', sa.Text(), server_default='en', nullable=False),
    sa.Column('version', sa.Text(), nullable=False),
    sa.Column('based_on', sa.Text(), nullable=False),
    sa.Column('generated_at', sa.Text(), nullable=False),
    sa.Column('source_guideline_version', sa.Text(), nullable=True),
    sa.Column('source_execution_id', sa.Text(), nullable=True),
    sa.Column('tree_json', sa.Text(), nullable=False),
    sa.Column('draft_tree_json', sa.Text(), nullable=True),
    sa.Column('draft_updated_at', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['disease_slug'], ['diseases.slug'], name=op.f('fk_care_pathways_disease_slug_diseases'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('disease_slug', name=op.f('pk_care_pathways'))
    )
    op.create_table('content_prs',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('disease_slug', sa.Text(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('opened', sa.Text(), nullable=False),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('author', sa.Text(), server_default='AI Watcher', nullable=False),
    sa.Column('reviewer', sa.Text(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('citations_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('diff_json', sa.Text(), server_default='[]', nullable=False),
    sa.Column('papers_json', sa.Text(), server_default='[]', nullable=False),
    sa.ForeignKeyConstraint(['disease_slug'], ['diseases.slug'], name=op.f('fk_content_prs_disease_slug_diseases')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_content_prs'))
    )
    op.create_table('guideline_documents',
    sa.Column('disease_slug', sa.Text(), nullable=False),
    sa.Column('version', sa.Text(), nullable=False),
    sa.Column('locale', sa.Text(), server_default='en', nullable=False),
    sa.Column('section_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('last_reviewed', sa.Text(), nullable=True),
    sa.Column('sections_json', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['disease_slug'], ['diseases.slug'], name=op.f('fk_guideline_documents_disease_slug_diseases'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('disease_slug', name=op.f('pk_guideline_documents'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('guideline_documents')
    op.drop_table('content_prs')
    op.drop_table('care_pathways')
    op.drop_table('diseases')
    op.drop_table('catalog_stats')
    # ### end Alembic commands ###
