"""content-translation scaffolding: content_translations + guideline_synthesis_translations

Revision ID: e2f9a1c7b4d3
Revises: c1b7a4e8f0d2
Create Date: 2026-07-22 09:30:00.000000

PR1 (foundation, NO behaviour change) of the content-translation architecture
(INSTALL-1). Two new, empty, unreferenced tables — nothing reads or writes them
yet:

* ``content_translations`` — a generic sidecar for machine translations of
  *relational scalar* content fields. One row per (entity_type, entity_id,
  field, locale). The English source stays authoritative in its own column;
  ``source_hash`` fingerprints the English text a translation was made from so a
  read can detect staleness and fall back to English per-field. Declared as a
  Core ``Table`` in ``backend/shared/persistence/schema.py`` (and mirrored in the
  legacy raw DDL in ``backend/content_db.py``).

* ``guideline_synthesis_translations`` — a row-per-locale sibling of
  ``guideline_synthesis`` for the document-shaped synthesis. Mirrors only the
  translatable fields; structural/provenance fields are joined from the English
  row so they can never drift per language. ORM-mapped against the shared
  ``MetaData`` in ``backend/guidelines/orm.py``.

Hand-written rather than autogenerated: the shared ``MetaData`` carries several
tables that are still created by the legacy raw-DDL path (not by any migration),
so ``--autogenerate`` against a fresh database proposes spurious CREATE TABLEs
for them. The ops below match the schema.py / orm.py definitions exactly.

Generic column types only (Text / Integer / JSON) so the same DDL is valid on
SQLite (offline alembic / tests) and Postgres (production). ``render_as_batch``
is enabled in env.py; these are plain CREATE TABLEs so batch mode is a no-op.

Deploy note: ``export DB_URL`` before ``alembic upgrade head``.
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "e2f9a1c7b4d3"
down_revision: Union[str, Sequence[str], None] = "c1b7a4e8f0d2"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.create_table(
        "content_translations",
        sa.Column("id", sa.Text(), nullable=False),
        sa.Column("entity_type", sa.Text(), nullable=False),
        sa.Column("entity_id", sa.Text(), nullable=False),
        sa.Column("field", sa.Text(), nullable=False),
        sa.Column("locale", sa.Text(), nullable=False),
        sa.Column("text", sa.Text(), nullable=False),
        sa.Column("source_hash", sa.Text(), nullable=False),
        sa.Column("source_model", sa.Text(), server_default="", nullable=False),
        sa.Column("translated_at", sa.Text(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_content_translations")),
        sa.UniqueConstraint(
            "entity_type",
            "entity_id",
            "field",
            "locale",
            name=op.f("uq_content_translations_entity_field_locale"),
        ),
    )
    op.create_index(
        "ix_content_translations_entity_locale",
        "content_translations",
        ["entity_type", "entity_id", "locale"],
        unique=False,
    )

    op.create_table(
        "guideline_synthesis_translations",
        sa.Column("disease_slug", sa.Text(), nullable=False),
        sa.Column("locale", sa.Text(), nullable=False),
        sa.Column("title", sa.Text(), nullable=False),
        sa.Column("based_on", sa.Text(), nullable=False),
        sa.Column("synth_disclaimer", sa.Text(), nullable=False),
        sa.Column("source_hash", sa.Text(), nullable=False),
        sa.Column("translated_at", sa.Text(), nullable=False),
        sa.Column("sections", sa.JSON(), nullable=False),
        sa.Column("what_to_do_now", sa.JSON(), nullable=True),
        sa.Column("red_flags", sa.JSON(), nullable=True),
        sa.Column("source_version", sa.Text(), server_default="", nullable=False),
        sa.Column("source_model", sa.Text(), server_default="", nullable=False),
        sa.PrimaryKeyConstraint(
            "disease_slug", "locale", name=op.f("pk_guideline_synthesis_translations")
        ),
    )


def downgrade() -> None:
    """Downgrade schema."""
    op.drop_table("guideline_synthesis_translations")
    op.drop_index(
        "ix_content_translations_entity_locale",
        table_name="content_translations",
    )
    op.drop_table("content_translations")
